### ISSUE TITLE
IndexError in active report

### ISSUE THREAD

**Issue by nblock** [vit-project/vit#186]
Vit crashes with "IndexError: list index out of range" in the active report:

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/vit/bin/vit", line 11, in <module>
    load_entry_point('vit==2.0.0a1', 'console_scripts', 'vit')()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/application.py", line 74, in __init__
    self.loop.run()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/wimp.py", line 648, in keypress
    return self._current_widget.keypress(size, key)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/application.py", line 64, in keypress
    return super().keypress(size, key)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/base_list_box.py", line 116, in keypress
    self.list_action_executed(size, key)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 544, in list_action_executed
    self.event.emit('task-list:keypress', data)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/event.py", line 16, in emit
    listener(data)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 46, in task_list_keypress
    self.update_header(data['size'])
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 103, in update_header
    self.update_project_column_header(size)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 117, in update_project_column_header
    self.set_project_column_header()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 123, in set_project_column_header
    (columns_widget, _) = self.header.original_widget.contents[column_index]
IndexError: list index out of range
```

Steps to reproduce:

* Have at least one active task
* Open vit's `active` report
* Press either `j`, `k`, `up`, or `down`

Vit: 2.x (1d06fdbaa86b09a6d7b4d0b69843fb597a1ceee8)

Some trivial shell script to quickly generate test data:

```sh
#!/bin/sh

set -e
set -u

TMP_DIR="$(mktemp --directory --suffix .vit)"
VIT_DIR="$TMP_DIR/vit"
TASK_DIR="$TMP_DIR/task"
TASKRC="$TMP_DIR/taskrc"

# task
mkdir "$TASK_DIR"
cat > "$TASKRC" <<EOT
data.location=$TASK_DIR
EOT
export TASKRC

# vit
mkdir "$VIT_DIR"
touch "$VIT_DIR/config.ini"

# create some tasks
task add a
task add b
task +LATEST start
task add c
task +LATEST start

echo "TASKRC: $TASKRC"
echo "VIT_DIR: $VIT_DIR"
```

**Comment by thehunmonkgroup** [comment]
I'm not able to reproduce.

That code deals with updating the project column header when a report has a project column, it's sorted by project ascending, and the ```indent_subprojects``` config setting is enabled (the default).

By default, TaskWarrior's active report orders by project ascending, and contains the project column, and this seems to all work fine in my testing.

Have you customized your active report?

**Comment by thehunmonkgroup** [comment]
OK, there was an edge case where if a report is sorted by project ascending but does *not* contain a project column, VIT would crash.

This has been fixed in https://github.com/scottkosty/vit/commit/ffa7d9ac05f27338dc3df7432be200d469ee4d4b -- see if that corrects your issue.

**Comment by nblock** [comment]
Crash still happens with ffa7d9ac05f27338dc3df7432be200d469ee4d4b.

* `pip install git+https://github.com/scottkosty/vit@ffa7d9ac05f27338dc3df7432be200d469ee4d4b`
* Generate test data using the above script
* Open vit's `active` report
* Navigate

All settings are default/unconfigured due to `VIT_DIR` and `TASKRC` environment variables. AFAIK, those two variables are enough to separate from my normal installation.

Traceback:
```bash
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/vit/bin/vit", line 11, in <module>
    load_entry_point('vit==2.0.0a1', 'console_scripts', 'vit')()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/application.py", line 74, in __init__
    self.loop.run()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/wimp.py", line 648, in keypress
    return self._current_widget.keypress(size, key)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/application.py", line 64, in keypress
    return super().keypress(size, key)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/base_list_box.py", line 116, in keypress
    self.list_action_executed(size, key)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 544, in list_action_executed
    self.event.emit('task-list:keypress', data)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/event.py", line 16, in emit
    listener(data)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 46, in task_list_keypress
    self.update_header(data['size'])
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 103, in update_header
    self.update_project_column_header(size)
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 117, in update_project_column_header
    self.set_project_column_header()
  File "/home/user/.pyenv/versions/3.7.3/envs/vit/lib/python3.7/site-packages/vit/task_list.py", line 123, in set_project_column_header
    (columns_widget, _) = self.header.original_widget.contents[column_index]
IndexError: list index out of range
```

**Comment by thehunmonkgroup** [comment]
OK, the problem was a report could have a project column configured, but still not output the column if it's completely empty. 

https://github.com/scottkosty/vit/commit/d9cc44de72689e53dd7b23f4364131c9b9575a39 adds a test for the existence of the project column after empty columns have been cleaned.

Should fix your issue, lemme know.

**Comment by thehunmonkgroup** [comment]
By the way, would you mind if I included that script you posted in the official codebase? I think it could be enhanced and come in handy for debugging purposes.

**Comment by nblock** [comment]
Works fine now, thx!

Sure, include the script.

**Comment by ipwnponies** [comment]
Are you sure this is fixed? I can reproduce on `2.0.0` with the testing script with this appended command:
```sh
task +LATEST modify project:foo && vit active
```

This results in the same error as initial report. I've verified my `vit` installation has the code changes in https://github.com/scottkosty/vit/commit/d9cc44de72689e53dd7b23f4364131c9b9575a39 fix.
```
Traceback (most recent call last):
  File "/Users/jngu/.local/share/virtualenv/bin/vit", line 11, in <module>
    sys.exit(main())
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/vit/application.py", line 74, in __init__
    self.loop.run()
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/main_loop.py", line 818, in _loop
    self._entering_idle()
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/main_loop.py", line 779, in _entering_idle
    callback()
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/main_loop.py", line 574, in entering_idle
    self.draw_screen()
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/main_loop.py", line 588, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/wimp.py", line 641, in render
    self._update_overlay(size, focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/wimp.py", line 621, in _update_overlay
    canv = self._original_widget.render(size, focus=focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/wimp.py", line 602, in render
    canv = self.__super.render(size, focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/widget.py", line 1761, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/vit/task_list.py", line 496, in render
    self.event.emit('task-list:size:change', data)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/vit/event.py", line 16, in emit
    listener(data)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/vit/task_list.py", line 385, in size_changed
    self.update_header(data['new_size'])
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/vit/task_list.py", line 104, in update_header
    self.update_project_column_header(size)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/vit/task_list.py", line 122, in update_project_column_header
    self.set_project_column_header(parents)
  File "/Users/jngu/.local/share/virtualenv/lib/python3.7/site-packages/vit/task_list.py", line 130, in set_project_column_header
    (columns_widget, _) = self.header.original_widget.contents[column_index]
IndexError: list index out of range
```

Setting `indent_subprojects = False` works around this. I can open a new ticket but this might be yet another edge case that was unaccounted for.

**Comment by thehunmonkgroup** [comment]
This one really has been brutal...

Project column index was not being calculated correctly with some column cleaning scenarios.

Hopefully https://github.com/scottkosty/vit/commit/811c480ce9fa491cf419e04310bf49cbe7093e2d will put this one to bed for good, please test.

**Comment by ipwnponies** [comment]
@thehunmonkgroup  just tested it out and it's working now, thanks!
